### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mohsinalimat** [GeekTree0101/VEditorKit#34]
Hello,

I am trying to create demo using this editor kit but when I try to run this fatal error give me. Please see below image I have attach.

![screenshot 2019-01-11 at 11 54 55 am](https://user-images.githubusercontent.com/973676/51016891-fd929d80-1597-11e9-846a-69b1d0dfc050.png)

Thanks,
Mohsinali Matiya

**Comment by GeekTree0101** [comment]
Thank you, this repo still beta version. i will fix this bug as soon as possible.

**Comment by GeekTree0101** [comment]
Uhmm i guess your viewController wrong initialized about super class

**Comment by GeekTree0101** [comment]
Can you show me your source code about class init parts

**Comment by mohsinalimat** [comment]
class NoteEditVC:  ASViewController<VEditorNode> {
    
    struct Const {
        static let defaultContentInsets: UIEdgeInsets =
            .init(top: 15.0, left: 5.0, bottom: 15.0, right: 5.0)
        static let ogObjectContainerInsets: UIEdgeInsets =
            .init(top: 10.0, left: 10.0, bottom: 10.0, right: 10.0)
        static let placeholderTextStyle: VEditorStyle = .init([.font(UIFont.systemFont(ofSize: 16)),
                                                               .minimumLineHeight(24.0),
                                                               .color(.lightGray)])
    }
    let controlAreaNode: EditorControlAreaNode
    let disposeBag = DisposeBag()
    let isEditMode: Bool
    let xmlString: String?
    
    init(isEditMode: Bool = true, xmlString: String? = nil) {
        let rule = EditorRule()
        self.controlAreaNode = EditorControlAreaNode(rule: rule)
        self.isEditMode = isEditMode
        self.xmlString = xmlString
        super.init(node: .init(editorRule: rule, controlAreaNode: controlAreaNode))
        self.title = isEditMode ? "Editor": "Preview"
        self.node.delegate = self
        self.controlAreaNode.isHidden = !isEditMode
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupNavigationBarButtonItem()
        self.loadXMLContent()
        self.rxAlbumAccess()
        self.rxLinkInsert()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
}

**Comment by GeekTree0101** [comment]
Oh you have to inhert `ASViewController<VEditorNode>`

### Wrong
```swift
class NoteEditVC: ASViewController {
```

### Expect
```swift
class NoteEditVC: ASViewController<VEditorNodE> {
````

**Comment by mohsinalimat** [comment]
ok let me check

**Comment by GeekTree0101** [comment]
If you wanna more information about ASViewController, http://texturegroup.org/docs/containers-asviewcontroller.html follow this link. Thank you your request

**Comment by mohsinalimat** [comment]
do that below line
class NoteEditVC: ASViewController<VEditorNode> {}

but same result

**Comment by GeekTree0101** [comment]
Did you try to clean & build?

**Comment by mohsinalimat** [comment]
Try to create new project then add pod install VEditorKit then create edit view controller subclass of ASViewController<VEditorNode>

then you know error...
